version: "3"
services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "3050:80"
  client:
    tty: true
    build: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  api:
    tty: true
    build: ./server
