version: "3"
services:
  nginx:
    image: "ram2510/vignesh-blog-nginx"
    ports:
      - "3050:80"
  client:
    image: "ram2510/vignesh-blog-client"
  api:
    image: "ram2510/vignesh-blog-server"
    env_file:
      - ./server/.env
  editor:
    image: "ram2510/vignesh-blog-editor"
    ports:
      - "4000:4000"
