version: "3"
services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "3050:80"
  client:
    tty: true
    build:
      context: ./client
      dockerfile: dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  api:
    tty: true
    build:
      context: ./server
      dockerfile: dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    env_file:
      - ./server/server.env
  editor:
    tty: true
    build:
      context: ./editor
      dockerfile: dockerfile.dev
    volumes:
      - /app/node_modules
      - ./editor:/app
